### ISSUE TITLE
Mail deletion breaks the server

### ISSUE THREAD

**Issue by mauricedoepke** [Timshel/maildev#1]
Steps to reproduce 
1. Send an email to maildev
2. Check the /email endpoint -> email is there as expected
3. Delete the email via api or the ui
4. Send another email to maildev
5. Check the /email endpoint -> returns status code 404 and an empty array

This works in the original maildev and thus seems to be an issue of the rewrite

**Comment by Timshel** [comment]
Hey,
Sorry missed the issue, will have a look :)

**Comment by Timshel** [comment]
Ok I believe I found the issue, will take a look at another issue I missed and probably make a release tomorrow.

Again really sorry, had invalid notification settings :(.

**Comment by Timshel** [comment]
Should be fixed in `3.0.0-rc2`

**Comment by mauricedoepke** [comment]
Thank you
